# Generated by Django 5.2.7 on 2025-10-26 17:07

import archives.models
import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Archives'},
        ),
        migrations.AddField(
            model_name='archive',
            name='audio',
            field=models.FileField(blank=True, help_text='For audio-type archives (max 5MB)', null=True, upload_to='archives/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a']), archives.models.validate_audio_size]),
        ),
        migrations.AddField(
            model_name='archive',
            name='caption',
            field=models.CharField(blank=True, default='', help_text='Required: Caption with copyright/source information', max_length=500),
        ),
        migrations.AddField(
            model_name='archive',
            name='circa_date',
            field=models.CharField(blank=True, help_text="Optional: Approximate date (e.g., 'c1910', 'around 1910s')", max_length=100),
        ),
        migrations.AddField(
            model_name='archive',
            name='document',
            field=models.FileField(blank=True, help_text='For document-type archives (max 5MB)', null=True, upload_to='archives/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt']), archives.models.validate_document_size]),
        ),
        migrations.AddField(
            model_name='archive',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Thumbnail for videos/audio (optional)', null=True, upload_to='archives/featured/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), archives.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='archive',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admin approval status'),
        ),
        migrations.AddField(
            model_name='archive',
            name='location',
            field=models.CharField(blank=True, help_text='Optional: Where the photo/artifact was taken/found', max_length=255),
        ),
        migrations.AddField(
            model_name='archive',
            name='original_author',
            field=models.CharField(blank=True, help_text='Optional: Original photographer/creator (e.g., Northcote Thomas)', max_length=255),
        ),
        migrations.AddField(
            model_name='archive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='video',
            field=models.FileField(blank=True, help_text='For video-type archives (max 50MB)', null=True, upload_to='archives/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'mov']), archives.models.validate_video_size]),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Required for images: Alt text for accessibility', max_length=255),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], help_text='Required: Type of archive', max_length=20),
        ),
        migrations.AlterField(
            model_name='archive',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.category'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='date_created',
            field=models.DateField(blank=True, help_text='Optional: Exact date if known', null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='description',
            field=models.TextField(help_text='Required: Detailed description (plain text)'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='image',
            field=models.ImageField(blank=True, help_text='For image-type archives', null=True, upload_to='archives/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), archives.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='archive',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.CharField(help_text='Required: Archive title', max_length=255),
        ),
        migrations.AlterField(
            model_name='archive',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to=settings.AUTH_USER_MODEL),
        ),
    ]
