# Generated by Django 4.2.25 on 2025-10-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_alter_archive_options_archive_audio_archive_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='is_featured',
        ),
    ]
