# Generated by Django 5.2.7 on 2025-10-26 17:07

import books.models
import django.core.validators
import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='content',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='alternate_cover',
            field=models.ImageField(blank=True, help_text='Alternate edition cover (optional)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), books.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='content_json',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, help_text='Block-based review content using Editor.js', null=True),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='cover_image_back',
            field=models.ImageField(blank=True, help_text='Back cover (optional)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), books.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='legacy_content',
            field=models.TextField(blank=True, help_text='Legacy HTML content'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='pending_approval',
            field=models.BooleanField(default=False, help_text='Review is pending admin approval'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When review was submitted for approval', null=True),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='author',
            field=models.CharField(help_text='Book author(s)', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Primary book cover', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), books.models.validate_file_size]),
        ),
    ]
