# Generated by Django 5.2.7 on 2025-10-26 17:07

import django.core.validators
import django.db.models.deletion
import django_editorjs_fields.fields
import insights.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_alter_archive_options_archive_audio_archive_caption_and_more'),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insightpost',
            name='content',
        ),
        migrations.AddField(
            model_name='editsuggestion',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Admin reason for rejection'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='content_json',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, help_text='Block-based content using Editor.js', null=True),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='copyright_info',
            field=models.CharField(blank=True, help_text='Copyright or image source', max_length=500),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Image caption with copyright/source info', max_length=500),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='image_description',
            field=models.TextField(blank=True, help_text='Detailed image description'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='legacy_content',
            field=models.TextField(blank=True, help_text='Legacy HTML content'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='pending_approval',
            field=models.BooleanField(default=False, help_text='Post is pending admin approval'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='submit_as_archive',
            field=models.BooleanField(default=True, help_text='Submit uploaded images as archives'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When post was submitted for approval', null=True),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='insights/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), insights.models.validate_file_size]),
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='insights/uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), insights.models.validate_file_size])),
                ('caption', models.CharField(help_text='Required: Caption with copyright/source', max_length=500)),
                ('description', models.TextField(help_text='Required: Image description')),
                ('alt_text', models.CharField(help_text='Alt text for accessibility', max_length=255)),
                ('archive_title', models.CharField(blank=True, max_length=255)),
                ('archive_type', models.CharField(default='image', max_length=20)),
                ('original_author', models.CharField(blank=True, help_text='e.g., Northcote Thomas', max_length=255)),
                ('date_created_field', models.DateField(blank=True, null=True)),
                ('circa_date', models.CharField(blank=True, help_text='e.g., c1910, around 1910s', max_length=100)),
                ('approved_as_archive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.category')),
                ('archive_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.archive')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='insights.insightpost')),
            ],
        ),
    ]
